[config]

[templates.hyprland]
input_path = '~/.config/matugen/templates/hyprland.conf'
output_path = '~/.config/hypr/theme_custom.conf'

[templates.equibop]
input_path = '~/.config/matugen/templates/discord.css'
output_path = '~/.config/equibop/settings/quickCss.css'
post_hook = 'python ~/dotfiles/.config/matugen/scripts/discord_updater.py ~/.config/equibop/settings/quickCss.css'

[templates.pywalfox]
input_path = '~/.config/matugen/templates/pywalfox.json'
output_path = '~/.cache/wal/colors.json'
post_hook = 'pywalfox update'